### ISSUE TITLE
Circle not always in the center 

### ISSUE THREAD

**Issue by pguso** [pguso/js-plugin-circliful#171]
See #168 for more details

**Comment by nebhead** [comment]
Just checking in to see you've had a chance to look into this one?  BTW, my project is coming along nicely and I'd love to share a quick video of the interface with you.  

Thanks again for making something awesome!

**Comment by nebhead** [comment]
GOOD NEWS!  (I think)

OK, so I think I might have resolved the issue for me, but I'm not sure if this is the _right_ solution.  Today I decided to poke around in the developer tools in chrome to see if I could debug the issue and I might have found the culprit.  

Here's what the HTML looks like and the circles that I am drawing.  

![circle-00](https://user-images.githubusercontent.com/19876886/91519323-1a7fff80-e8a7-11ea-8f29-f40a46b2a0f6.png)

I noticed that compared to the viewBox size (115), the x and y coordinates appeared to be off.  So just for fun, I thought I would change those x and y coordinates to see if I could correct the values to half the viewBox size.  This is what happened: 

![circle-01](https://user-images.githubusercontent.com/19876886/91519429-6f237a80-e8a7-11ea-9d45-2e3da1581a70.png)

And it totally worked!  Except the foreground circle is out of place, which makes sense because I didn't alter those values.  Then I got to wondering why the viewBox was sized at 115.  So I decided to try to change it to 100.  Here was what happened:

![circle-02](https://user-images.githubusercontent.com/19876886/91519496-a4c86380-e8a7-11ea-8837-61f67781365b.png)

So, now everything is lined up properly.  Time to dig deeper, so I looked at your code for getting/setting the viewBox parameters and this is what I see:

![circle-03](https://user-images.githubusercontent.com/19876886/91519551-ce818a80-e8a7-11ea-88d0-4e070acae01d.png)

There appears to be some code here that adds 1.5* the width of the background circle which happens to be 10 (so that would be where the extra 15 is coming from in the viewBox size of 115).  Thus I decided, let's try to remove that code.  And sure enough, it seems to be working.  It's filling the entire viewBox, which is totally fine for my needs.  

![circle-04](https://user-images.githubusercontent.com/19876886/91519665-16a0ad00-e8a8-11ea-9f0e-1c4772999f9f.png)

I'm testing now, with my current installation and everything seems to be going just fine.  So I think that I'll just continue using it this way.  

Let me know if this is a reasonable fix or if I'm missing something.  I can raise a pull request if you think it's appropriate.  

Thanks!
Ben.

**Comment by pguso** [comment]
Hey Ben,

Thank you very much for your support. Work is kind of stressful at the moment. This seams like a very good solution, it would be nice if you open up a pull request :)

And we’re can I find the video you mentioned before, I would really like to see your solution. In my profile you find my email address if you don’t want to share it here.

Thank you,
Patric

**Comment by nebhead** [comment]
Hey Patric!  Sorry to hear about work, I also have a stressful day job and can totally relate.  I'm sure things will get better and you'll get back to normal again.  Anyway, I've submitted the pull request and I hope that helps take a little off your plate.  Feel free to close this issue whenever you'd like.  

And I think for my project, I'm going to record a new video since I've done quite a few updates since the last time.  Once I'm done, I'll send it over to you for your viewing pleasure. :) 

Thanks!
Ben.

**Comment by pguso** [comment]
Hey Ben, thank you for your support, i merged your pull request. :)
